// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lagerstrom/goflower (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/client.go github.com/lagerstrom/goflower Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// PublishFailed mocks base method.
func (m *MockClient) PublishFailed(taskId, exception, traceback string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFailed", taskId, exception, traceback)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishFailed indicates an expected call of PublishFailed.
func (mr *MockClientMockRecorder) PublishFailed(taskId, exception, traceback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFailed", reflect.TypeOf((*MockClient)(nil).PublishFailed), taskId, exception, traceback)
}

// PublishReceived mocks base method.
func (m *MockClient) PublishReceived(taskName, args, rootId, taskId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishReceived", taskName, args, rootId, taskId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishReceived indicates an expected call of PublishReceived.
func (mr *MockClientMockRecorder) PublishReceived(taskName, args, rootId, taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishReceived", reflect.TypeOf((*MockClient)(nil).PublishReceived), taskName, args, rootId, taskId)
}

// PublishStarted mocks base method.
func (m *MockClient) PublishStarted(taskId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishStarted", taskId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishStarted indicates an expected call of PublishStarted.
func (mr *MockClientMockRecorder) PublishStarted(taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishStarted", reflect.TypeOf((*MockClient)(nil).PublishStarted), taskId)
}

// PublishSucceeded mocks base method.
func (m *MockClient) PublishSucceeded(taskId, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSucceeded", taskId, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSucceeded indicates an expected call of PublishSucceeded.
func (mr *MockClientMockRecorder) PublishSucceeded(taskId, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSucceeded", reflect.TypeOf((*MockClient)(nil).PublishSucceeded), taskId, result)
}
